services:
  https-portal:
    profiles:
      - production

  www-service:
    ports:
      - "8888:80"

  verdaccio:
    ports:
      - "4873:4873"

  piping-server:
    ports:
      - "8080:8080"

  presence-server:
    ports:
      - "8787:8787"
